version: '3'

services:
  database:
    build:
      context: ./database
    ports:
      - "33061:3306"
    environment:
      - MYSQL_DATABASE=demo-db
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "88:80"
      - "448:443"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
    links:
      - database:database
    volumes:
      - ../src:/var/www



